%{?!ros_distro:%global ros_distro rolling}
%global pkg_name libcamera
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-libcamera
Version:        0.7.0
Release:        3%{?dist}
Summary:        ROS %{pkg_name} package

License:        Apache-2.0 and BSD-2-Clause and BSD-3-Clause and GPL-2.0-or-later and LGPL-2.1-or-later
URL:            https://libcamera.org
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  meson

%{?bloom_package}

%description
An open source camera stack and framework for Linux, Android, and ChromeOS


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
An open source camera stack and framework for Linux, Android, and ChromeOS


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
An open source camera stack and framework for Linux, Android, and ChromeOS


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
# override macro
%define __meson_auto_features auto

# call meson executable instead of using the 'meson' macro to use default paths
%__meson setup \
    --prefix="%{bloom_prefix}" \
    --cmake-prefix-path="%{bloom_prefix}" \
    --libdir=lib \
    --libexecdir=lib \
    %{_vpath_builddir}
%meson_build


%install
%meson_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__ninja -C %{_vpath_builddir} -t targets | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
%meson_test || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Tue Apr 28 2026 Christian Rauch <Rauch.Christian@gmx.de> - 0.7.0-3
- Autogenerated by Bloom

* Tue Apr 28 2026 Christian Rauch <Rauch.Christian@gmx.de> - 0.7.1-2
- Autogenerated by Bloom

* Tue Apr 28 2026 Christian Rauch <Rauch.Christian@gmx.de> - 0.7.1-1
- Autogenerated by Bloom

* Fri Apr 24 2026 Christian Rauch <Rauch.Christian@gmx.de> - 0.7.0-1
- Autogenerated by Bloom
